{ lib, modulesPath, ... }: {
  imports = [
    # Include the default lxd configuration.
    "${modulesPath}/virtualisation/lxc-container.nix"
    # Include the container-specific autogenerated configuration.
    ./incus.nix
    # Include the OrbStack-specific configuration.
    ./orbstack.nix
  ];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
