[base]
default = none
unknown-token = #D14D41,bold
; Such as ;, &, &&, ||, |
commandseparator = #6F6E69
; Such as >, >>, <, 2>, |&
redirection = #D0A215
; <<<
here-string-tri = #D0A215,bold
here-string-text = #87D3C3,bg:#122F2C
here-string-var = #92BFDB,bg:#122F2C,bold
; {fd}>file
exec-descriptor = #DFB431,bold
comment = #878580
correct-subtle = #5ABDAC
incorrect-subtle = #E8705F
subtle-separator = #6F6E69
subtle-bg= bg:#282726
secondary = base16
recursive-base = bg:#1C1B1A

[command-point]
; Such as if, then, else, fi, for, while, case
reserved-word = #D0A215,bold
; Command position when the token starts a subcommand context
subcommand = #D0A215
alias = #879A39,bold
suffix-alias = #879A39
global-alias = #FFFCF0,bg:#205EA6,bold
; Such as cd, echo, typeset, read
builtin = #879A39
function = #DA702C,bold
command = #879A39
; Precommand modifiers such as command, builtin, exec, noglob
precommand = #D0A215
hashed-command = #879A39
single-sq-bracket = #879A39,bold
double-sq-bracket = #879A39,bold
double-paren = #D0A215,bold

[paths]
path = #CE5D97
; / inside paths
pathseparator = #6F6E69
path-to-dir = #CE5D97,underline
globbing = #4385BE,bold
globbing-ext = #8B7EC8,bold

[brackets]
paired-bracket = #FFFCF0,bg:#205EA6,bold
bracket-level-1 = #879A39,bold
bracket-level-2 = #D0A215,bold
bracket-level-3 = #3AA99F,bold

[arguments]
single-hyphen-option = #3AA99F
double-hyphen-option = #3AA99F,bold
back-quoted-argument = #CE5D97
single-quoted-argument = #D0A215
double-quoted-argument = #D0A215
dollar-quoted-argument = #D0A215
optarg-string = #3AA99F
optatg-number = #8B7EC8

[in-string]
back-dollar-quoted-argument = #3AA99F,bold
back-or-dollar-double-quoted-argument = #4385BE,bold

[other]
variable = #4385BE
assign = #6F6E69
assign-array-bracket = #879A39,bold
history-expansion = #4385BE,bold

[math]
mathvar = #4385BE,bold
mathnum = #8B7EC8
matherr = #D14D41,bold

[for-loop]
forvar = #4385BE
fornum = #8B7EC8
foroper = #D0A215
forsep = #6F6E69,bold

[case]
case-input = #4385BE
case-parentheses = #D0A215,bold
case-condition = #CECDC3,bg:#164F4A

