$mod = SUPER
$mouseleft = mouse:272
$mouseright = mouse:273
$mouseside = mouse:275
$mouseextra = mouse:276

source = ~/.config/hypr/config/animations.conf
source = ~/.config/hypr/config/autostart.conf
source = ~/.config/hypr/config/environment.conf
source = ~/.config/hypr/config/keybinds.conf
source = ~/.config/hypr/config/monitor.conf
source = ~/.config/hypr/config/variables.conf
source = ~/.config/hypr/config/windowrules.conf

