profile=high-quality
hwdec=auto
deband=yes
cscale=catmull_rom
icc-profile-auto=yes
target-colorspace-hint=yes
blend-subtitles=video
audio-file-auto=fuzzy
sub-auto=fuzzy
keep-open=yes
save-position-on-quit=yes
watch-later-options=start,vid,aid,sid
