source = ~/.config/hypr/config/defaults.conf

# https://wiki.hyprland.org/Configuring/Keywords/#executing

exec-once = waybar
exec-once = hyprpaper
# exec-once = hypridle
exec-once = fcitx5 -d
exec-once = mako
exec-once = nm-applet --indicator
exec-once = bash -c "mkfifo /tmp/$HYPRLAND_INSTANCE_SIGNATURE.wob && tail -f /tmp/$HYPRLAND_INSTANCE_SIGNATURE.wob | wob & disown"
exec-once = systemctl --user start hyprpolkitagent
exec-once = hyprlauncher -d

# Slow app launch fix
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

