# Cursor
envd = HYPRCURSOR_THEME,Tahoe
envd = HYPRCURSOR_SIZE,18
envd = XCURSOR_SIZE,18
envd = QT_CURSOR_SIZE,18
# XDG Specifications
envd = XDG_CURRENT_DESKTOP,Hyprland
envd = XDG_SESSION_TYPE,wayland
envd = XDG_SESSION_DESKTOP,Hyprland
# Toolkit backend
envd = GDK_BACKEND,wayland,x11,*
envd = SDL_VIDEODRIVER,wayland
envd = CLUTTER_BACKEND,wayland
# QT
envd = QT_AUTO_SCREEN_SCALE_FACTOR,1
envd = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
envd = QT_QPA_PLATFORM,wayland;xcb
envd = QT_QPA_PLATFORMTHEME,gtk3
# NVIDIA
envd = GBM_BACKEND,nvidia-drm
envd = __GLX_VENDOR_LIBRARY_NAME,nvidia
envd = LIBVA_DRIVER_NAME,nvidia
envd = __GL_GSYNC_ALLOWED,1
envd = __GL_VRR_ALLOWED,1
envd = NVD_BACKEND,direct
# Increase Nvidia's shader cache size to 12GB
envd = __GL_SHADER_DISK_CACHE_SIZE,12000000000
# Electron based apps use X11 as default, auto should detect wayland
envd = ELECTRON_OZONE_PLATFORM_HINT,auto
