# https://wiki.hyprland.org/Configuring/Monitors

monitor = , preferred, auto, 1
monitorv2 {
    output = DP-2
    mode = 2560x1440@144
    position = auto
    scale = 1
    bitdepth = 10
    supports_wide_color = 0
    supports_hdr = 0
}

