# Windows Rules: https://wiki.hypr.land/Configuring/Window-Rules
# Worlspace Rules: https://wiki.hypr.land/Configuring/Workspace-Rules

# Float Necessary Windows
windowrule = match:class mpv, float on
windowrule = match:class org.pulseaudio.pavucontrol, float on
windowrule = match:title ^(Enter name of file to save to)(.*)$, float on
windowrule = match:title ^Save (File|Image)(.*)$, float on
windowrule = match:title ^(Open File)(.*)$, float on
windowrule = match:title ^(Opening)(.*)$, float on
windowrule = match:class ^(xdg-desktop-portal-gtk|xdg-desktop-portal-kde|xdg-desktop-portal-hyprland)(.*)$, float on
windowrule = match:class ^(polkit-gnome-authentication-agent-1|hyprpolkitagent|org.org.kde.polkit-kde-authentication-agent-1)(.*)$, float on
windowrule = match:class CachyOSHello, float on
windowrule = match:class zenity, float on
windowrule = match:title Steam - Self Updater, float on
windowrule = match:class steam_app_0, float on

windowrule {
    name = Picture in Picture
    match:title = ^Picture-in-Picture.*$
    float = on
    size = 960 540
    move = (monitor_w * 0.6) (monitor_h * 0.2)
}
windowrule {
    name = Media
    match:title = ^(imv|mpv|danmufloat|termfloat|nemo|ncmpcpp)$
    float = on
    size = 960 540
    center = on
}

# Steam game fullscreen
windowrule {
    name = Steam games
    match:class = ^(steam_app_\d\d+|gamescope)$
    fullscreen = on
    workspace = emptynm
}
windowrule {
    name = Proton games
    match:xdg_tag = proton-game
    fullscreen = on
    workspace = emptynm
}

# Smart gaps https://wiki.hyprland.org/Configuring/Workspace-Rules/#smart-gaps
# Decorations related to tiling windows on workspaces 1 to 10
workspace = w[tv1]s[true], gapsout:0, gapsin:0, rounding:true
windowrule = match:float off, match:workspace w[tv1]s[false], border_size 0
windowrule = match:float off, match:workspace w[tv1]s[false], rounding 0
windowrule = match:float on, match:workspace w[fv1-99], border_color $sky_500, border_size 3, rounding 6
# Decorations related to fullscreen workdpaces
workspace = f[1], gapsout:0, gapsin:0, rounding:0

# Tryout scrolling
workspace = 1, layout:scrolling

# Special workspace
workspace = special:special, on-created-empty:$terminal

# Layer
layerrule = match:namespace logout_dialog, animation slide top
layerrule = match:namespace wallpaper, animation fade 50%
layerrule = match:namespace waybar, animation slide down

